name: Code Linter

on: push

jobs:
  resharper-core-lint:
    name: Clean up C# code base via R# CLT
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RESHARPER_PROFILE_NAME: "TAP Cleanup"
      MAIN_SOLUTION_NAME: "./Lagalike.sln"
      PROJECT_WORKING_DIRECTORY: "./"

    steps:
      - uses: actions/checkout@v2
      - run: git pull
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.301'
      - name: Setup ReSharper Command Line Tools
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools --version 2021.2.0-eap06
      - name: Clean up codebase via ReSharper Command Line Tools
        run: jb cleanupcode --profile="${{ env.RESHARPER_PROFILE_NAME }}" ${{ env.MAIN_SOLUTION_NAME }}
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "[Bot] Automated ReSharper CLT update"